### ISSUE TITLE
Integrating with drone ci

### ISSUE THREAD

**Issue by XPLOT1ON** [appleboy/drone-line#72]
Hi, 
How do I add this plugin to existing drone ci? Also, is it possible to store line developer credentials in the server itself not in `drone.yml`. And does your plugin supports sending to multiple LineUID?

**Comment by appleboy** [comment]
See: https://github.com/appleboy/drone-line/blob/master/DOCS.md

Send to multiple LineUID:

```yml
pipeline:
  line:
    image: appleboy/drone-line
    channel_secret: xxxxxxxxxx
    channel_token: xxxxxxxxxx
    to:
      - user id 1
      - user id 2
```
